<?php
session_start();
$apiKey = "rzp_test_lkE1lPOYakvjhu";
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" type="text/css" href="payment.css">
</head>
<body>
    <div class="heading-container">
           <a href="index.html"><img src="images/logo.png"></a> 
        </div>

<div class="payment-container">
    <div class="column">
    <div class="main-container">
        <div>
            <input type="text" name="name" value="<?php echo $_SESSION['name']; ?>"  readonly>
        </div>  
        <div>
            <input type="email" name="mail" value="<?php echo $_SESSION['test']; ?>" readonly >
        </div>
        <div>
            <input type="text" name="amount" value="<?php echo $_SESSION['amount']; ?>" readonly>
        </div>

        <div>
          <form method="POST" action="timer.php">
            <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_SESSION['amount']*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'. rand(10,100). 'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay now"
    data-name="EV Chargers"
    data-description="Pay to Charge"
    data-image="images/logo.png"
    data-prefill.email="<?php echo $_SESSION['test']; ?>"
    data-prefill.contact="<?php echo $_SESSION['contact']; ?>"
    data-theme.color="#0fd64f"
    callback_url="http://localhost/echargers2/user.php"
    >
    </script>
    <input type="hidden" custom="Hidden Element" name="hidden">
    </form>
       </div>
            
</div>
</div>
</div>

</body>
</html>
